// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgbrftultwlfkwtbcghm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnYnJmdHVsdHdsZmt3dGJjZ2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1ODg4NTMsImV4cCI6MjA1MzE2NDg1M30.qH2ihDxdylSwGC2sAo_3a_KiVvPXMSlpIWOkaqVVCGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);